config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'landing#index'
  resources :products do
    resources :reviews
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, presence: true
  validates :cost, presence: true
  validates :origin, presence: true
  before_save(:titleize_product)
  before_save(:round_decimal)

  scope :most_recent, -> { order(created_at: :desc).limit(3)}

  scope :most_reviews, -> {(
    select("products.id, products.name, count(reviews.id) as reviews_count")
    .joins(:reviews)
    .group("products.id")
    .order("reviews_count DESC")
    .limit(1)
  )}



  private
    def titleize_product
      self.name = self.name.titleize
      self.origin = self.origin.titleize
    end

    def round_decimal
      self.cost = self.cost.round(2)
    end
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :author, presence: true
  validates :rating, presence: true
  validates :content, presence: true
  validates :rating, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5}
  validates_length_of :content, minimum: 50, maximum: 250 
  before_save(:titleize_review)

  private
  def titleize_review
    self.author = self.author.titleize
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # before_action :configure_permitted_parameters, if: :devise_controller?
  # helper_method :authenticate_admin

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user_params|
      user_params.permit({roles: [] },:admin, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController

  def index
    @products = Product.all
    @most_reviewed = Product.most_reviews
    @most_recently_added = Product.most_recent
    render :index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :only => [:new, :destroy, :edit] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end
  
  def index
    @products = Product.order(:name).page(params[:page])
    @user = current_user
  end

  def new
    @product = Product.new 
    render :new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "Product successfully added!"
      redirect_to products_path
    else
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    render :edit
  end

  def show
    @product = Product.find(params[:id])
    @user = current_user
    render :show
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "Product successfully updated!"
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.destroy
      flash[:notice] = "Product successfully deleted!"
      redirect_to products_path
    else
      render :edit
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :cost, :origin)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :only => [:destroy, :edit] do
    redirect_to new_user_session_path unless current_user && current_user.admin
  end

  def new
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new
    render :new
  end

  def create
    @product = Product.find(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review Successfully added!"
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    @user = current_user
    render :show
  end

  def edit
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    render :edit
  end

  def update
    @product = Product.find(params[:product_id])
    @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review successfully updated!"
      redirect_to product_path(@review.product)
    else
      render :edit
    end
  end

  def destroy
    @review = Review.find(params[:id])
    if @review.destroy
      flash[:notice] = "Review successfully deleted!"
      redirect_to product_path(@review.product)
    end
  end

  private
    def review_params
      params.require(:review).permit(:author, :content, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/index.html.erb
<div class="top">
<h1> Mario's Food Source </h1>
</div>
<hr>

<p>Welcome to Mario's Food Source! We like all the foods, but we especially like the Italian foods!  My dad started this store in 1943 when he moved here from Italy, and I have taken over the shop to let him get some much needed rest!</p>

<hr>

  <% if Product.most_reviews.any? %>
    <h4>Most Reviewed Product:</h4>
    <ul>
      <% Product.most_reviews.each do |product| %>
        <li><%= link_to product.name, product_path(product)%></li>
      <% end %>
    </ul>
  <% else %>
  <p>Write some reviews so we can display our most reviewed product here!</p>
  <% end %>

  <% if Product.most_recent.any? %>
    <h4>Most Recently Added:</h4>
    <ul>
      <% Product.most_recent.each do |product| %>
        <li><%= link_to product.name, product_path(product) %></li>
      <% end %>
    </ul>
  <% else %>
  <p>When we add new products, you'll see the most recently added right here!</p>
  <% end %>

  <%# <% if current_user || current_user && current_user.admin %>
    <p><%= link_to "View all produdcts", products_path %></p>
  <%# <% end %>
<%# <% else %>
  <%# <h4>Please Create an account to view this site!</h4> %>



<%# <% if current_user && current_user.admin %>
  <p><%= link_to "Create new product!", new_product_path %></p>
<%# <% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_product_form.html.erb
<%= render "layouts/errors", :object => @product %>

<%= form_for @product do |f| %>
  <%= f.label :Name %>
  <br>
  <%= f.text_field :name %>
  <br>
  <%= f.label :Cost %>
  <br>
  <%= f.text_field :cost %>
  <br>
  <%= f.label :Country_of_Origin %>
  <br>
  <%= f.text_field :origin%>
  <br>
  <%= f.submit %>
<% end %>

app/views/layouts/_review_form.hrml.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :Your_Name %>
  <br>
  <%= f.text_field :author %>
  <br>
  <%= f.label :Rating %>
  <br>
  <%= f.text_field :rating%>
  <br>
  <%= f.label :Your_Review %>
  <br>
  <%= f.text_area :content%>
  <br>
  <%= f.submit %>
<% end %>



  

app/views/layouts/_review_form.html.erb
<%= render "layouts/errors", :object => @review %>

<%= form_for [@product, @review] do |f| %>
  <%= f.label :Your_Name %>
  <br>
  <%= f.text_field :author %>
  <br>
  <%= f.label :Rating %>
  <br>
  <%= f.text_field :rating%>
  <br>
  <%= f.label :Your_Review %>
  <br>
  <%= f.text_area :content%>
  <br>
  <%= f.submit %>
<% end %>



  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarioFood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <br>
      <% if current_user %>
        <a href="/users/sign_out" data-method="delete" value="<%= destroy_user_session_path%>">| Sign Out | </a>
        <a href="/users/edit" value="<%= edit_user_registration_path %>">Edit Account |</a>
      <% else %>
        <%= link_to "Sign-in or Sign-up", new_user_session_path %>
      <% end %>

      <%= flash[:alert] %>
      <%= flash[:notice] %>
      <%= yield %>
      </div>
  </body>
</html>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render "layouts/product_form" %>

app/views/products/index.html.erb
<div class="top">
<h1> Mario's Food Source </h1>
</div>

<% if @products.any? %>
  <ul>
    <% @products.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
  <% paginate @products %>
<% else %>
  <p>There are no product yet!</p>
<% end %>


<%# <% if current_user && current_user.admin %>
<p><%= link_to "Create a new product!", new_product_path %></p>
<%# <% end %>

<% if Product.most_reviews.any? %>
  <h4>Check out our most reviewed product!</h4>
  <ul>
    <% Product.most_reviews.each do |product| %>
      <li><%= link_to product.name, product_path(product)%></li>
    <% end %>
  </ul>
<% else %>
<p>Write some reviews so we can display our most reviewed product here!</p>
<% end %>

<% if Product.most_recent.any? %>
  <h4>Check out our most recently added items!</h4>
  <ul>
    <% Product.most_recent.each do |product| %>
      <li><%= link_to product.name, product_path(product) %></li>
    <% end %>
  </ul>
<% else %>
<p>When we add new products, you'll see the most recently added right here!</p>
<% end %>

<%# <% if current_user || current_user.admin %>
  <p><%= link_to "Return to Home Page", root_path %></p>
<%# <% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render "layouts/product_form" %>

app/views/products/show.html.erb
<div class="top">
<h1>Product: <%= @product.name %></h1>
<h3>Cost: $<%= @product.cost %></h3>
<h3>Country of Origin: <%= @product.origin%></h3>
</div>

<% if @product.reviews.any? %>
  <h4>Click on a buyer's name to read their review:</h4>
  <% @product.reviews.each do |review| %>
    <ul>
      <li><%= link_to review.author, product_review_path(@product, review) %></li>
    </ul>
  <% end %>
<% else %>
  <p>No reviews for this product... Be the first to leave a review!</p>
<% end %>

<%# <% if current_user || current_user.admin %>
  <p><%= link_to "Add a Review!", new_product_review_path(@product) %></p>
  <p><%= link_to "Return to products", products_path %></p>
  <p><%= link_to "Return to Home Page", root_path %></p>
<%# <% end %>

<%# <% if current_user.admin %>
  <p><%= link_to "Edit Product", edit_product_path(@product) %></p>
  <p><%= link_to "Delete Product", product_path(@product),
                            :data => {:confirm => "Are you sure?",
                                      :method => "Delete"} %></p>
<%# <% end %>

app/views/reviews/edit.html.erb
<h1>Edit Review</h1>

<%= render "layouts/review_form" %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render "layouts/review_form" %>

app/views/reviews/show.html.erb
<h1>Author: <%= @review.author %></h1>
<h2>Review For: <%= @product.name %></h2>
<h2>Product Rating: <%= @review.rating %>/5</h2>
<h4><%= @review.content %></h4>

<%# <% if current_user.admin %>
  <p><%= link_to "Edit Review", edit_product_review_path(@product, @review) %></p>
  <p><%= link_to "Delete Review", product_review_path(@product, @review),
                        :data => {:confirm => "Are you sure?",
                                       :method => "delete"} %></p>
<%# <% end %>

<%# <% if current_user || current_user.admin %>
  <p><%= link_to "Return to Product", product_path(@product) %></p>
  <p><%= link_to "Return to Home Page", root_path %></p>                                   
<%# <% end %>